question_bank_1 = {
        "Name the 2 quarterbacks taken before Josh Allen in the 2018 NFL draft": "Baker Mayfield and Sam Darnold",
        "Name all 4 quarterbacks taken in the first round of the 2020 NFL draft": "Joe Burrow, Justin Herbert, Tua Tagovailoa and Jordan Love",
        "Which player broke the record for most pass attempts in a single season?": "Tom Brady",
        "Which player has the most combined rushing and receiving touchdowns of all time?": "Jerry Rice",
        "Which team drafted Sam Bradford": "St. Louis Rams",
        "Which NFL team drafted Drew Brees?": "LA Chargers",
        "Name the youngest player to win NFL MVP": "Lamar Jackson",
        "Which Cowboys player had a controversial catch ruled incomplete in the 2014 playoffs?": "Dez Bryant",
        "Name the 3 players with the most rushing yards in NFL history": "Walter Payton, Frank Gore and Emmitt Smith",
        "Name the 4 wide receivers taken before Justin Jefferson in the 2020 NFL draft": "Jalen Reagor, Henry Ruggs, Jerry Jeudy andCeeDee Lamb",
        "Who won offensive rookie of the year from the 2021 NFL draft class?": "Ja'Marr Chase",
        "Who won defensive rookie of the year from the 2021 NFL draft class?": "Micah Parsons",
        "Who is the last LA Chargers player to win MVP?": "LaDainian Tomlinson",
        "Which team originally traded for Antonio Brown until he refused to play for them?": "Buffalo Bills",
        "Name the 3 players with the most 200+ yard rushing games of all time": "Derrick Henry, Adrian Peterson and OJ Simpson",
        "Who is the fastest player to reach 20,000 career passing yards? ": "Patrick Mahomes",
        "Which quarterback has the most rushing yards in a single game?": "Justin Fields",
        "Which player has the record for most touchdown catches in a single season?": "Randy Moss",
        "Who is the KC Chief's franchise leader in receiving yards?": "Tony Gonzalez",
        "Which team drafted the most Heisman Trophy winners?": "Detroit Lions",
        "Name the player that tied an NFL record by rushing for 6 touchdowns in a single game in 2020": "Alvin Kamara",
        "Who was the only receiver to catch a touchdown pass in 4 Superbowl's?": "Jerry Rice",
        "Who was the first pick in the 2022 NFL draft?": "Trevon Walker",
        "Which coach won 100 games with 2 different franchises?": "Andy Reid",
        "Name the 3 quarterbacks taken before Justin Fields in the 2021 NFL draft": "Trevor Lawrence, Trey Lance and Zach Wilson",
        "Which player led the NFL in sacks for the 2022 season?": "Nick Bosa",
        "Which team has the most Hall of Famers all time?": "Chicago Bears",
        "Which quarterback has the most second half passing yards in a single game in the NFL 2022 season?": "Kirk Cousins",
        "Name the player that has the record for most catches in their rookie year": "Jaylen Waddle",
        "Which team drafted Kirk Cousins?": "Washington Commanders",
        "Which NFL team has the longest playoff drought?": "New York Jets",
        "Who was the first quarterback to have back to back 1000 yard rushing seasons?": "Lamar Jackson",
        "Name the players who have the highest rushing, passing and receiving yards in Lions franchise history": "Barry Sanders, Matthew Stafford and Calvin Johnson",
        "Which team drafted Amari Cooper?": "Oakland Raiders",
        "Which two players completed the Minneapolis Miracle?": "Case Keenum and Stefon Diggs",
        "Name the player with the record for the most catches in a single game": "Brandon Marshall",
        "Which two teams did Peyton Manning beat to win the Superbowl?": "Carolina Panthers and Chicago Bears",
        "Name the only NFL quarterback to throw 6 touchdowns in back to back games": "Ben Roethlisberger",
        "Name the all time leading receiver for the Pittsburgh Steelers": "Hines Ward",
        "Name the fastest quarterback to reach 30,000 passing yards": "Matthew Stafford",
        "Name the Titans player that threw a touchdown pass to himself": "Marcus Mariota",
        "Who is the highest scoring quarterback-receiver duo of all time?": "Peyton Manning and Marvin Harrison",
        "Which team originally drafted Phillip Rivers?": "NY Giants",
        "Who is the all time leader in receiving touchdowns for the Dallas Cowboys": "Dez Bryant",
        "Name the player that won 3 consecutive NFL MVPs": "Brett Favre",
        "Name the NFL head coach that was suspended for a whole season for running a bounty program": "Sean Payton",
        "Name the 2 quarterbacks who won a Superbowl with 2 different teams": "Tom Brady and Peyton Manning",
        "Name the only quarterback who threw for 30 touchdowns and 30 interceptions in a single season": "Jameis Winston",
        "Name the 4 teams who have never been to a Superbowl": "Lions, Browns, Texans and Jaguars",
        "Which player holds the record for most single season receptions?": "Michael Thomas",
        "Which tight end has the most touchdown catches in NFL history?": "Antonio Gates",
        "Which NFL player was fined 8200 for kicking a punter in the face?": "Antonio Brown",
        "Name every team Tom Brady has beaten in the Superbowl": "Seahawks, Eagles, Falcons, Chiefs, Rams and Panthers",
        "Which player has the most kickoff return touchdowns of all time?": "Cordarelle Patterson",
        "Which player has the fastest 40 yard dash time in the NFL combine?": "John Ross",
        "Name the quarterback and receiver that completed the Philly Special in Superbowl 52": "Nick Foles and Trey Burton",
        "What college did Ryan Fitzpatrick play at?": "Harvard ",
        "Name the player that rushed for a record 296 yards in a single game": "Adrian Peterson",
        "What team did the 49ers beat in two different Superbowls?": "Cincinati Bengals",
        "Name the only team that hasn't had a quarterback throw for 4000 yards in a season": "Chicago Bears",
        "Who has the record for most rushing touchdowns in Jaguars franchise history?": "Maurice Jones Drew",
        "Name all 7 teams that Adrian Peterson played for": "Viking, Commanders, Cardinals, Titans, Lions, Seahawks and Saints",
        "Which team did Marshawn Lynch start his career with?": "Buffalo Bills",
        "Who has the record for most passing yards in their first NFL game?": "Cam Newton",
        "Name the only 4 quarterbacks to beat all 32 teams": "Tom Brady, Drew Brees, Peyton Manning and Brett Favre",
        "Name 4 running backs that have broke 2000 rushing yards in a single season": "Derrick Henry, Jamal Lewis, Chris Johnson, Erik Dickerson, Barry Sanders, Terrell Davis, OJ Simpsonand Adrian Peterson",
        "Which NFL player injured his hand in a fireworks accident?": "Jason Pierre-Paul",
        "Who is the only player to ever return an opening kickoff in the Superbowl for a touchdown?": "Devin Hester",
        "Which team has had only 3 head coaches since 1969?": "Steelers",
        "Which NFL team's tradition is breaking tables before games?": "Buffalo Bills",
        "Which team holds the record for most points in a single season?": "Denver Broncos",
        "Name the NFL team that has a pool in their stadium": "Jacksonville Jaguars",
        "Which NFL coach has the most wins of all time?": "Don Schula",
        "Which former NFL player famously celebrated a touchdown by throwing popcorn at their face?": "Terrell Owens",
        "Name all 4 NFL teams who's mascot is a big cat": "Panthers, Bengals, Jaguars and Lions",
        "Who has the record for most catches in a Super Bowl?": "James White",
        "Which NFL team went a whole season without throwing a touchdown to a wide reciever?": "Kansas City Chiefs",
        "Name the only player to record back to back 200+ yard receiving games": "Josh Gordon",
        "How many minutes is an overtime period in the NFL?": "10 minutes",
        "Name the only player to be selected in the first round of the NFL and MLB draft": "Kyler Murray",
        "Name the quarterback in the 2017 draft that was drafted before Patrick Mahomes and Deshaun Watson": "Mitchell Trubisky",
        "Who is the youngest quarterback to win a Superbowl?": "Ben Roethlisburger",
        "Name the 5 NFL teams that have birds as mascots": "Philadelphia Eagles, Atlanta Falcons, Seattle Seahawks, Arizona Cardinals, and Baltimore Ravens",
        "Name the only NFL logo that faces left": "Philadelphia Eagles",
        "What team was cast as the Gotham Rogues in the movie The Dark Knight Rises?": "Pittsburgh Steelers",
        "Which NFL team plays at Soldier Field?": "Chicago Bears",
        "Name the NFL player with the most fumbles of all time": "Brett Favre",
        "Name the first wide receiver to have 2000 yards combined in the regular and post season": "Cooper Kupp",
        "Name the first NFL team to lose 16 games in the regular season": "Detroit Lions",
        "Who is the first NFL quarterback to rush for 1000 yards?": "Michael Vick"
}